[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solstice = "EsjGSxfqv9jtBDWmUpPypj58uatCaqppPD7sCULujXAu"  # 필요하면 실제 Devnet 배포 후 업데이트

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
